# brew bundle
#
#
# CLI tools
brew "neovim"
brew "git-delta"
brew "gh"
brew "wezterm"
brew "jless"
brew "lazygit"
brew "lazydocker"
brew "docker"
brew "xh"
brew "font-jetbrains-mono"
brew "fzf"
brew "starship"
brew "zoxide"
brew "node"

# GUI apps
# cask "slack"
# cask "rider"
cask "google-chrome"
cask "spotify"
cask "microsoft-teams"
cask "bitwarden"
cask "dbeaver-community"
cask "dotnet-sdk"
cask "visual-studio-code"

