require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.telescope"
require "user.lsp"
require "user.cmp"
require "user.treesitter"
require "user.nvim-tree"
require "user.autopairs"
require "user.comment"
require "user.indentline"
require "user.colorizer"
require "user.colorscheme"
-- require "statusline"
require("kanagawa").setup()
-- pcall(vim.cmd, "colorscheme " .. "kanagawa")
